"""Views — the library-of-views generated by mpa-view.

Each view is a function `prepare(payload, **opts) -> dict` that converts
a raw library-cell payload into a JSON-serialisable dict the UI renders.
The HTTP server in `server.py` knows view names; views know nothing
about HTTP.
"""
